version: 1
default_environment: dev
environments:
  - name: dev
  - name: prod
    config:
      plugins:
        extractors:
          - name: tap-postgres--td-database
            config:
              ssl: true
        loaders:
          - name: target-postgres--dwh
            config:
              ssl: true

project_id: 8a35e99a-f240-4ef5-96aa-b5687139b894
plugins:
  extractors:
    - name: tap-postgres--td-database
      inherit_from: tap-postgres
      variant: transferwise
      pip_url: pipelinewise-tap-postgres==1.8.3
      select:
        - default$default-Company.*
        - default$default-CompanyAssociation.*
        - default$default-User.*
        - default$default-Form.*
        - default$default-Bsda.*
        - default$default-Bsdasri.*
        - default$default-Bsff.*
        - default$default-Bsvhu.*
        - default$default-EcoOrganisme.*
        - default$default-BsffPackaging.*
      metadata:
        "*":
          replication-method: INCREMENTAL
          replication-key: updatedAt
        default$default-CompanyAssociation:
          replication-method: FULL_TABLE
        default$default-EcoOrganisme:
          replication-method: FULL_TABLE
        default$default-BsffPackaging:
          replication-method: FULL_TABLE

    - name: tap-google-sheets
      variant: singer-io
      pip_url: git+https://github.com/singer-io/tap-google-sheets.git
    - name: tap-google-sheets--gerep
      inherit_from: tap-google-sheets
      config:
        start_date: 2021/01/01

    - name: tap-zammad
      namespace: tap_zammad
      pip_url: "tap-zammad==0.0.3"
      executable: tap-zammad
      capabilities:
        - state
        - catalog
        - discover
      config:
        auth_token:
        api_base_url:
        start_date:
      select:
        - "*.*"
      metadata:
        tickets:
          replication-method: INCREMENTAL
          replication-key: updated_at
        users:
          replication-method: INCREMENTAL
          replication-key: updated_at
        organizations:
          replication-method: INCREMENTAL
          replication-key: updated_at
        groups:
          replication-method: FULL_TABLE

  loaders:
    - name: target-postgres--dwh
      inherit_from: target-postgres
      variant: transferwise
      pip_url: pipelinewise-target-postgres==2.1.2
    - name: target-postgres--dwh-trackdechets
      inherit_from: target-postgres--dwh
      config:
        default_target_schema: raw_zone_trackdechets

    - name: target-postgres--dwh-zammad
      inherit_from: target-postgres--dwh
      config:
        default_target_schema: raw_zone_zammad

  transformers:
    - name: dbt-postgres
      variant: dbt-labs
      pip_url: dbt-core~=1.4.1 dbt-postgres~=1.4.1
      commands:
        source__raw_zone:
          args: source freshness
          description: Check the freshness of raw_zone_trackdechets
        run__trusted_zone_trackdechets:
          args: run --select @trusted_zone.trackdechets
          description: Run trusted_zone_trackdechets models
        run__trusted_zone_insee:
          args: run --select @trusted_zone.insee
          description: Run dbt 'trusted_zone.insee' models
        run__trusted_zone_icpe:
          args: run --select @trusted_zone.icpe
          description: Run dbt 'trusted_zone.icpe' models
        run__trusted_zone_zammad:
          args: run --select @trusted_zone.zammad
          description: Run dbt 'trusted_zone.zammad' models
        test__trusted_zone_trackdechets:
          args: test --select trusted_zone.trackdechets
          description: Run trusted_zone_trackdechets models

  utilities:
    - name: sqlfluff
      variant: sqlfluff
      pip_url: sqlfluff==2.0.0a4 sqlfluff-templater-dbt==2.0.0a4 dbt-core dbt-postgres
      settings:
        - name: user
        - name: password
          kind: password
        - name: schema
        - name: database

jobs:
  - name: elt--td-database
    tasks:
      - tap-postgres--td-database target-postgres--dwh-trackdechets
      - dbt-postgres:source__raw_zone
      - dbt-postgres:run__trusted_zone_trackdechets
      - dbt-postgres:test__trusted_zone_trackdechets
  - name: transform-icpe
    tasks:
      - dbt-postgres:source__raw_zone
      - dbt-postgres:run__trusted_zone_icpe
  - name: transform-insee
    tasks:
      - dbt-postgres:source__raw_zone
      - dbt-postgres:run__trusted_zone_insee
  - name: elt--zammad
    tasks:
      - tap-zammad target-postgres--dwh-zammad
      - dbt-postgres:run__trusted_zone_zammad

schedules:
  - name: daily-elt-td-database
    interval: "@daily"
    job: elt--td-database
  - name: weekly-transform-icpe
    interval: 0 3 * * *
    job: transform-icpe
  - name: monthly-transform-insee
    interval: 0 20 1 * *
    job: transform-insee
  - name: daily-elt-zammad
    interval: "@daily"
    job: elt--zammad
