version: 1
default_environment: dev
environments:
  - name: dev
  - name: prod
    config:
      plugins:
        extractors:
          - name: tap-postgres--td-database
            config:
              ssl: true
        loaders:
          - name: target-postgres--dwh
            config:
              ssl: true

project_id: 8a35e99a-f240-4ef5-96aa-b5687139b894
plugins:
  extractors:
    - name: tap-postgres--td-database
      inherit_from: tap-postgres
      variant: transferwise
      pip_url: pipelinewise-tap-postgres==1.8.3
      select:
        - default$default-Company.*
        - default$default-CompanyAssociation.*
        - default$default-User.*
        - default$default-Form.*
        - default$default-Bsda.*
        - default$default-Bsdasri.*
        - default$default-Bsff.*
        - default$default-Bsvhu.*
      metadata:
        "*":
          replication-method: INCREMENTAL
          replication-key: updatedAt
        default$default-CompanyAssociation:
          replication-method: FULL_TABLE

    - name: tap-google-sheets
      variant: singer-io
      pip_url: git+https://github.com/singer-io/tap-google-sheets.git

    - name: tap-google-sheets--gerep
      inherit_from: tap-google-sheets
      config:
        spreadsheet_id: 1uzcWPJhpcQCbbVbW7f6UA2XpD0zJ7Iqb
        start_date: "2021/01/01"

  loaders:
    - name: target-postgres--dwh
      inherit_from: target-postgres
      variant: transferwise
      pip_url: pipelinewise-target-postgres==2.1.1
  transformers:
    - name: dbt-postgres
      variant: dbt-labs
      pip_url: dbt-core~=1.1.0 dbt-postgres~=1.1.0
      commands:
        run_analytics:
          args: run --select analytics
          description: Run dbt 'analytics' package
        run_icpe:
          args: run --select icpe
          description: Run dbt 'icpe' package

jobs:
  - name: sync-td-database
    tasks:
      - tap-postgres--td-database target-postgres--dwh
      - dbt-postgres:run_analytics
  - name: transform-icpe
    tasks:
      - dbt-postgres:run_icpe
schedules:
  - name: daily-td-db-sync
    interval: "@daily"
    job: sync-td-database
  - name: weekly-transform-icpe
    interval: "0 0 1 * *"
    job: transform-icpe
