version: 1
default_environment: dev
environments:
  - name: dev
  - name: prod
    config:
      plugins:
        extractors:
          - name: tap-postgres--td-database
            config:
              ssl: true
        loaders:
          - name: target-postgres--dwh
            config:
              ssl: true

project_id: 8a35e99a-f240-4ef5-96aa-b5687139b894
plugins:
  extractors:
    - name: tap-postgres--td-database
      inherit_from: tap-postgres
      variant: transferwise
      pip_url: pipelinewise-tap-postgres==1.8.3
      select:
        - default$default-Company.*
        - default$default-CompanyAssociation.*
        - default$default-User.*
        - default$default-Form.*
        - default$default-Bsda.*
        - default$default-Bsdasri.*
        - default$default-Bsff.*
        - default$default-Bsvhu.*
      metadata:
        "*":
          replication-method: INCREMENTAL
          replication-key: updatedAt
        default$default-CompanyAssociation:
          replication-method: FULL_TABLE

    - name: tap-google-sheets
      variant: singer-io
      pip_url: git+https://github.com/singer-io/tap-google-sheets.git

    - name: tap-google-sheets--gerep
      inherit_from: tap-google-sheets
      config:
        spreadsheet_id: 1uzcWPJhpcQCbbVbW7f6UA2XpD0zJ7Iqb
        start_date: "2021/01/01"

  loaders:
    - name: target-postgres--dwh
      inherit_from: target-postgres
      variant: transferwise
      pip_url: pipelinewise-target-postgres==2.1.1
    - name: target-postgres--dwh-trackdechets
      inherit_from: target-postgres--dwh
      config:
        default_target_schema: "raw_zone_trackdechets"

  transformers:
    - name: dbt-postgres
      variant: dbt-labs
      pip_url: dbt-core~=1.3.0 dbt-postgres~=1.3.0
      commands:
        source__raw_zone_trackdechets:
          args: source freshness
          description: Check the freshness of raw_zone_trackdechets
        run__trusted_zone_trackdechets:
          args: run --select trusted_zone.trackdechets
          description: Run trusted_zone_trackdechets models
        test__trusted_zone_trackdechets:
          args: test --select *.trackdechets
          description: Run trusted_zone_trackdechets models
        run_analytics:
          args: run --select refined_zone.analytics
          description: Run dbt 'analytics' package
        run_icpe:
          args: run --select refined_zone.icpe
          description: Run dbt 'icpe' package
jobs:
  - name: elt--td-database
    tasks:
      - tap-postgres--td-database target-postgres--dwh-trackdechets
      - dbt-postgres:source__raw_zone_trackdechets
      - dbt-postgres:run__trusted_zone_trackdechets
      - dbt-postgres:test__trusted_zone_trackdechets
  - name: transform-icpe
    tasks:
      - dbt-postgres:run_icpe
schedules:
  - name: daily-elt-td-database
    interval: "@daily"
    job: elt--td-database
  - name: weekly-transform-icpe
    interval: "0 3 * * *"
    job: transform-icpe
