version: 1
default_environment: dev
environments:
  - name: dev
    config:
      plugins:
        utilities:
          - name: elementary
            config:
              project_dir: ${MELTANO_PROJECT_ROOT}/transform/
          - name: dbt-osmosis
            config:
              adapter: postgres

  - name: prod
    config:
      plugins:
        extractors:
          - name: tap-postgres--td-database
            config:
              ssl: true
        loaders:
          - name: target-postgres--dwh
            config:
              ssl: true

project_id: 8a35e99a-f240-4ef5-96aa-b5687139b894
plugins:
  extractors:
    - name: tap-postgres--td-database
      inherit_from: tap-postgres
      variant: transferwise
      pip_url: pipelinewise-tap-postgres==1.8.3
      select:
        - default$default-Company.*
        - default$default-CompanyAssociation.*
        - default$default-User.*
        - default$default-Form.*
        - default$default-Bsda.*
        - default$default-Bsdasri.*
        - default$default-Bsff.*
        - default$default-Bsvhu.*
        - default$default-EcoOrganisme.*
        - default$default-BsffPackaging.*
        - default$default-BsddRevisionRequest.*
        - default$default-BsdaRevisionRequest.*
        - default$default-VhuAgrement.*
        - default$default-TransporterReceipt.*
        - default$default-BrokerReceipt.*
        - default$default-TraderReceipt.*
        - default$default-BsddTransporter.*
      metadata:
        "*":
          replication-method: INCREMENTAL
          replication-key: updatedAt
        default$default-CompanyAssociation:
          replication-method: FULL_TABLE
        default$default-EcoOrganisme:
          replication-method: FULL_TABLE
        default$default-BsffPackaging:
          replication-method: FULL_TABLE
        default$default-VhuAgrement:
          replication-method: FULL_TABLE
        default$default-TransporterReceipt:
          replication-method: FULL_TABLE
        default$default-BrokerReceipt:
          replication-method: FULL_TABLE
        default$default-TraderReceipt:
          replication-method: FULL_TABLE

    - name: tap-zammad
      namespace: tap_zammad
      pip_url: tap-zammad==0.0.4
      executable: tap-zammad
      capabilities:
        - state
        - catalog
        - discover
      config:
        auth_token:
        api_base_url:
        start_date:
      select:
        - "*.*"
      metadata:
        tickets:
          replication-method: INCREMENTAL
          replication-key: updated_at
        users:
          replication-method: INCREMENTAL
          replication-key: updated_at
        organizations:
          replication-method: INCREMENTAL
          replication-key: updated_at
        groups:
          replication-method: FULL_TABLE

    - name: tap-google-sheets
      variant: matatika
      pip_url: git+https://github.com/Matatika/tap-google-sheets.git
    - name: tap-google-sheets--matching_td_georisques
      inherit_from: tap-google-sheets
      config:
        sheet_id: 1DDkQ6NfBi7dGXd7LxUxDFg_LVYAnS-WmzYIHCax2pxg
        key_properties:
          - code_aiot
      select:
        - "!*.trai*"
        - "*.*"
      metadata:
        "*":
          replication-method: FULL_TABLE
    - name: tap-google-sheets--referentiel_codes_operation_rubriques
      inherit_from: tap-google-sheets
      config:
        sheet_id: 16o0U3A6unTT2XqFTQ6mDg7cySE2-JeWoUO4wFrS7b2g
        key_properties:
          - code_operation
          - rubrique
      metadata:
        "*":
          replication-method: FULL_TABLE

  loaders:
    - name: target-postgres--dwh
      inherit_from: target-postgres
      variant: transferwise
      pip_url: pipelinewise-target-postgres==2.1.2
    - name: target-postgres--dwh-trackdechets
      inherit_from: target-postgres--dwh
      config:
        default_target_schema: raw_zone_trackdechets
    - name: target-postgres--dwh-zammad
      inherit_from: target-postgres--dwh
      config:
        default_target_schema: raw_zone_zammad
    - name: target-postgres--dwh-gsheet
      inherit_from: target-postgres--dwh
      config:
        default_target_schema: raw_zone_gsheet
        primary_key_required: false

    - name: target-clickhouse
      variant: shaped-ai
      pip_url: git+https://github.com/shaped-ai/target-clickhouse.git
  transformers:
    - name: dbt-postgres
      variant: dbt-labs
      pip_url: dbt-core~=1.5.2 dbt-postgres~=1.5.2 shandy-sqlfmt[jinjafmt] dbt-osmosis
      commands:
        run__trusted_zone_trackdechets:
          args: run --select trusted_zone.trackdechets+
          description: Run trusted_zone_trackdechets models
        run__trusted_zone_insee:
          args: run --select trusted_zone.insee+
          description: Run dbt 'trusted_zone.insee' models
        run__trusted_zone_icpe:
          args: run --select trusted_zone.icpe+
          description: Run dbt 'trusted_zone.icpe' models
        run__trusted_zone_zammad:
          args: run --select trusted_zone.zammad+
          description: Run dbt 'trusted_zone.zammad' models
        run__trusted_zone_gsheet:
          args: run --select trusted_zone.gsheet+
          description: Run dbt 'trusted_zone.gsheet' models
        test__trusted_zone_trackdechets:
          args: test --select @trusted_zone.trackdechets
          description: Test trusted_zone_trackdechets models

  utilities:
    - name: sqlfluff
      variant: sqlfluff
      pip_url: sqlfluff~=2.1.2 sqlfluff-templater-dbt~=2.1.2 dbt-core dbt-postgres
      settings:
        - name: user
        - name: password
          kind: password
        - name: schema
        - name: database

    - name: elementary
      variant: elementary
      pip_url: elementary-data[postgres]==0.8.2 git+https://github.com/potloc/elementary-ext.git
      config:
        profiles_dir: ${MELTANO_PROJECT_ROOT}/transform/profiles/postgres/
        project_dir: ${MELTANO_PROJECT_ROOT}/transform/
        file-path: ${MELTANO_PROJECT_ROOT}/output/elementary/elementary.html

    - name: dbt-osmosis
      namespace: dbt_postgres
      variant: z3z1ma
      pip_url: dbt-osmosis dbt-postgres
      config:
        adapter: postgres
      commands:
        refactor:
          args: yaml refactor --profiles-dir transform/profiles/postgres --project-dir transform
          description: Run yaml refactor command
jobs:
  - name: elt--td-database
    tasks:
      - tap-postgres--td-database target-postgres--dwh-trackdechets
      - dbt-postgres:freshness
      - dbt-postgres:run__trusted_zone_trackdechets
      - dbt-postgres:test__trusted_zone_trackdechets
      - dbt-postgres:docs-generate
      - elementary:monitor-report
  - name: transform-icpe
    tasks:
      - dbt-postgres:run__trusted_zone_icpe
      - dbt-postgres:docs-generate
      - elementary:monitor-report
  - name: transform-insee
    tasks:
      - dbt-postgres:freshness
      - dbt-postgres:run__trusted_zone_insee
      - dbt-postgres:docs-generate
      - elementary:monitor-report
  - name: elt--zammad
    tasks:
      - tap-zammad target-postgres--dwh-zammad
      - dbt-postgres:run__trusted_zone_zammad
      - dbt-postgres:docs-generate
      - elementary:monitor-report
  - name: elt--gsheet
    tasks:
      - tap-google-sheets--matching_td_georisques target-postgres--dwh-gsheet
      - tap-google-sheets--referentiel_codes_operation_rubriques target-postgres--dwh-gsheet
      - dbt-postgres:run__trusted_zone_gsheet

schedules:
  - name: daily-elt-td-database
    interval: "@daily"
    job: elt--td-database
  - name: daily-transform-icpe
    interval: "0 14 * * *"
    job: transform-icpe
  - name: monthly-transform-insee
    interval: "0 20 1 * *"
    job: transform-insee
  - name: daily-elt-zammad
    interval: "@daily"
    job: elt--zammad
  - name: daily-elt-gsheet
    interval: "@daily"
    job: elt--gsheet
