version: 2

sources:
  - name: raw_zone
    description: Tables qui ne correspondent à aucune catégorie spécifique.
    tables:
      - name: laposte_hexasmal
        description: >
          Une ligne par commune.
        columns:
          - name: code_commune_insee
            description: >
              Code commune correspondant à celui dans la base géographique des communes de l'INSEE.
            tests:
              - not_null
          - name: code_postal
            description: Code postal de la commune
            tests:
              - not_null
      - name: codes_operations_traitements
        description: >
          Une ligne par code opération traitement (codes R et D) avec la description de l'opération associée.
        columns:
          - name: code
            description: >
              Code opération traitement.
            tests:
              - not_null
              - unique
          - name: description
            description: Description de l'opération de traitement.
            tests:
              - not_null
              - unique

  - name: raw_zone_gsheet
    description: Tables qui proviennent de Google Sheet.
    tables:
      - name: collectivites_compentence_dechets
        description: >
          Une ligne par collectivite a competence dechet.
        columns:
          - name: siren_epci
            description: >
              Code SIREN de la collectivite.
            tests:
              - not_null
              - unique
      - name: collectivites
        identifier: coordonnees-epci-fp-2022-last
        description: >
          Une ligne par collectivite.
        columns:
          - name: SIREN
            quote: true
            description: >
              Code SIREN de la collectivite.
            tests:
              - not_null
              - unique
      - name: gerep_traiteurs
        identifier: gerep_2016_2017_traiteurs
        description: >
          Une ligne par annee, code dechet et etablissement traiteur.
      - name: gerep_producteurs
        identifier: gerep_2016_2017_producteurs
        description: >
          Une ligne par annee, code dechet et etablissement producteurs.

      - name: eco_organismes_agrees_2022
        description: >
          Une ligne par eco-organisme agréé et par filière.
        columns:
          - name: siret
            description: >
              Code SIRET de l'établissement.
            tests:
              - not_null

  - name: raw_zone_insee
    description: Données issues de l'open data INSEE
    loader: airflow
    tables:
      - name: naf2008
        description: >
          Une ligne par code sous-classe 
          de la nomenclature des activités françaises édition 2008.
        columns:
          - name: code_sous_classe
            description: Clé unique
            tests:
              - unique
              - not_null
      - name: arrondissement
        description: >
          Données géographiques INSEE des arrondissements français.
          Une ligne par code arrondissement.
        columns:
          - name: arr
            description: Code arrondissement
            tests:
              - unique
              - not_null
      - name: canton
        description: >
          Données géographiques INSEE des cantons français.
          Une ligne par identifiant canton.
        columns:
          - name: id_canton
            description: Code canton
            tests:
              - unique
              - not_null
      - name: commune
        description: >
          Données géographiques INSEE des communes françaises.
          Une ligne par code commune.
        columns:
          - name: com
            description: Code commune
            tests:
              - not_null
      - name: departement
        description: >
          Données géographiques INSEE des département français.
          Une ligne par code département.
        columns:
          - name: dep
            description: Code département
            tests:
              - unique
              - not_null
      - name: pays
        description: >
          Données géographiques INSEE des pays du monde.
          Une ligne par pays.
      - name: region
        description: >
          Données géographiques INSEE des régions françaises.
          Une ligne par région.
        columns:
          - name: reg
            description: Code région
            tests:
              - unique
              - not_null
      - name: stock_etablissement
        description: >
          Données des établissements français.
          Une ligne par établissement.
        columns:
          - name: siret
            description: Code région
            tests:
              - unique
              - not_null
  - name: raw_zone_icpe
    description: Données issues de Géorisques
    loader: airflow
    tables:
      - name: etablissements
        identifier: ic_etablissement
        description: >
          Permet de faire le lien entre les codes S3ic et les siret
        columns:
          - name: codeS3ic
            quote: true
            description: identifiant ICPE de l'installation
            tests:
              - not_null
      - name: installations_classees
        identifier: ic_installation_classee
        description: >
          Contient les autorisations pour chacune des installations classées 
          avec l'id vers l'entrée associée dans la nomenclature
        columns:
          - name: codeS3ic
            quote: true
            description: identifiant ICPE de l'installation
            tests:
              - not_null
      - name: nomenclature
        identifier: ic_ref_nomenclature_ic
        description: >
          Nomenclature des rubriques ICPE
        columns:
          - name: id
            description: id rubrique
            tests:
              - unique
              - not_null
  - name: raw_zone_zammad
    description: Données extraites de Zammad
    loader: meltano
    tables:
      - name: tickets
        description: >
          Données sur les tickets Zammad.
        columns:
          - name: id
            description: identifiant unique du ticket
            tests:
              - not_null
              - unique
      - name: tags
        description: >
          Contient la liste des tags pour chaque tickets. Une ligne par ticket ayant des tags.
        columns:
          - name: ticket_id
            description: identifiant du ticket
            tests:
              - not_null
      - name: users
        description: >
          Données des utilisateurs Zammad. Un utilisateur peut être aussi bien un utilisateur interne (membre de l'équipe)
          qu'un utilisateur externe (utilisateur de Trackdéchets ayant créé un ticket support).
        columns:
          - name: id
            description: identifiant unique de l'utilisateur
            tests:
              - unique
              - not_null
      - name: groups
        description: >
          Données groupes Zammad.
        columns:
          - name: id
            description: identifiant unique du groupe
            tests:
              - unique
              - not_null
