version: 2

sources:
  - name: raw_zone_trackdechets
    description: Replica de la base applicative Trackdéchets
    loader: meltano
    freshness:
      warn_after:
        count: 36
        period: hour
      error_after:
        count: 72
        period: hour
    loaded_at_field: "_sdc_batched_at"
    tables:
      - name: bsdd_raw
        identifier: form
        description: >
          Une ligne par BSDD, les BSDD supprimés restent dans la table.
        columns:
          - name: id
            description: Clé primaire
            tests:
              - unique
              - not_null
      - name: bsda_raw
        identifier: bsda
        description: >
          Une ligne par BSDA, les BSDA supprimés restent dans la table.
        columns:
          - name: id
            description: Clé primaire
            tests:
              - unique
              - not_null
      - name: bsdasri_raw
        identifier: bsdasri
        description: >
          Une ligne par BSDASRI, les BSDASRI supprimés restent dans la table.
        columns:
          - name: id
            description: Clé primaire
            tests:
              - unique
              - not_null
      - name: bsff_raw
        identifier: bsff
        description: >
          Une ligne par BSFF, les BSFF supprimés restent dans la table.
        columns:
          - name: id
            description: Clé primaire
            tests:
              - unique
              - not_null
      - name: bsvhu_raw
        identifier: bsvhu
        description: >
          Une ligne par BSVHU, les BSVHU supprimés restent dans la table.
        columns:
          - name: id
            description: Clé primaire
            tests:
              - unique
              - not_null
      - name: user_raw
        identifier: user
        description: >
          Une ligne par compte utilisateur.
        columns:
          - name: id
            description: Clé primaire
            tests:
              - unique
              - not_null
      - name: company_raw
        identifier: company
        description: >
          Une ligne par compte établissement.
        columns:
          - name: id
            description: Clé primaire
            tests:
              - unique
              - not_null
      - name: company_association_raw
        identifier: companyassociation
        description: >
          Une ligne par paire (company,user).
        columns:
          - name: id
            description: Clé primaire
            tests:
              - unique
              - not_null
      - name: eco_organisme_raw
        identifier: ecoorganisme
        description: >
          Table entrée en dur, Eco-Organismes qui nous sont connus.
        columns:
          - name: id
            description: Clé primaire
            tests:
              - unique
              - not_null
      - name: bsff_packaging_raw
        identifier: bsffpackaging
        description: >
          Table avec les données des contenants BSFF. Une ligne par contenant.
        columns:
          - name: id
            description: Clé primaire
            tests:
              - unique
              - not_null
          - name: bsffId
            description: ID du BSFF auquel le contenant est associé
            tests:
              - not_null

  - name: raw_zone_insee
    description: Données issues de l'open data INSEE
    loader: airflow
    tables:
      - name: naf2008
        description: >
          Une ligne par code sous-classe 
          de la nomenclature des activités françaises édition 2008.
        columns:
          - name: code_sous_classe
            description: Clé unique
            tests:
              - unique
              - not_null
      - name: arrondissement
        description: >
          Données géographiques INSEE des arrondissements français.
          Une ligne par code arrondissement.
        columns:
          - name: arr
            description: Code arrondissement
            tests:
              - unique
              - not_null
      - name: canton
        description: >
          Données géographiques INSEE des cantons français.
          Une ligne par identifiant canton.
        columns:
          - name: id_canton
            description: Code canton
            tests:
              - unique
              - not_null
      - name: commune
        description: >
          Données géographiques INSEE des communes françaises.
          Une ligne par code commune.
        columns:
          - name: com
            description: Code commune
            tests:
              - not_null
      - name: departement
        description: >
          Données géographiques INSEE des département français.
          Une ligne par code département.
        columns:
          - name: dep
            description: Code département
            tests:
              - unique
              - not_null
      - name: pays
        description: >
          Données géographiques INSEE des pays du monde.
          Une ligne par pays.
      - name: region
        description: >
          Données géographiques INSEE des régions françaises.
          Une ligne par région.
        columns:
          - name: reg
            description: Code région
            tests:
              - unique
              - not_null
      - name: stock_etablissement
        description: >
          Données des établissements français.
          Une ligne par établissement.
        columns:
          - name: siret
            description: Code région
            tests:
              - unique
              - not_null
  - name: raw_zone_icpe
    description: Données issues de Géorisques
    loader: airflow
    tables:
      - name: etablissements
        identifier: ic_etablissement
        description: >
          Permet de faire le lien entre les codes S3ic et les siret
        columns:
          - name: codeS3ic
            quote: true
            description: identifiant ICPE de l'installation
            tests:
              - not_null
      - name: installations_classees
        identifier: ic_installation_classee
        description: >
          Contient les autorisations pour chacune des installations classées 
          avec l'id vers l'entrée associée dans la nomenclature
        columns:
          - name: codeS3ic
            quote: true
            description: identifiant ICPE de l'installation
            tests:
              - not_null
      - name: nomenclature
        identifier: ic_ref_nomenclature_ic
        description: >
          Nomenclature des rubriques ICPE
        columns:
          - name: id
            description: id rubrique
            tests:
              - unique
              - not_null
  - name: raw_zone_zammad
    description: Données extraites de Zammad
    loader: meltano
    tables:
      - name: tickets
        description: >
          Données sur les tickets Zammad.
        columns:
          - name: id
            description: identifiant unique du ticket
            tests:
              - not_null
              - unique
      - name: tags
        description: >
          Contient la liste des tags pour chaque tickets. Une ligne par ticket ayant des tags.
        columns:
          - name: ticket_id
            description: identifiant du ticket
            tests:
              - not_null
      - name: users
        description: >
          Données des utilisateurs Zammad. Un utilisateur peut être aussi bien un utilisateur interne (membre de l'équipe)
          qu'un utilisateur externe (utilisateur de Trackdéchets ayant créé un ticket support).
        columns:
          - name: id
            description: identifiant unique de l'utilisateur
            tests:
              - unique
              - not_null
      - name: groups
        description: >
          Données groupes Zammad.
        columns:
          - name: id
            description: identifiant unique du groupe
            tests:
              - unique
              - not_null
