SELECT
    id,
    "name",
    created_at,
    created_by_id,
    updated_at,
    updated_by_id,
    active,
    assignment_timeout,
    email_address_id,
    follow_up_assignment,
    follow_up_possible,
    note,
    reopen_time_in_days,
    shared_drafts,
    signature_id,
    user_ids
FROM
    {{ source("raw_zone_zammad", "groups") }}
