{{ config(
  pre_hook = "{{ create_indexes_for_source([
    'createdAt',
    'updatedAt',
    'emitterCompanySiret',
    'transporterCompanySiret',
    'destinationCompanySiret',
    'wasteCode',
    'ecoOrganismeSiret',
    'transporterTakenOverAt',
    'destinationOperationDate'
  ]) }}"
) }}

with source as (
    select * from {{ source('raw_zone_trackdechets', 'bsdasri_raw') }}
),

renamed as (
    select
        id,
        status,
        "createdAt"                              as created_at,
        "updatedAt"                              as updated_at,
        "isDeleted"                              as is_deleted,
        "isDraft"                                as is_draft,
        "emitterCompanyName"                     as emitter_company_name,
        "emitterCompanySiret"                    as emitter_company_siret,
        "emitterCompanyAddress"                  as emitter_company_address,
        "emitterCompanyContact"                  as emitter_company_contact,
        "emitterCompanyPhone"                    as emitter_company_phone,
        "emitterCompanyMail"                     as emitter_company_mail,
        "emitterPickupSiteName"                  as emitter_pickup_site_name,
        "emitterPickupSiteAddress"               as emitter_pickup_site_address,
        "emitterPickupSiteCity"                  as emitter_pickup_site_city,
        "emitterPickupSitePostalCode"            as emitter_pickup_site_postal_code,
        "emitterPickupSiteInfos"                 as emitter_pickup_site_infos,
        "wasteCode"                              as waste_code,
        "wasteAdr"                               as waste_adr,
        "emitterWastePackagings"                 as emitter_waste_packagings,
        "emitterCustomInfo"                      as emitter_custom_info,
        "emitterEmissionSignatureAuthor"         as emitter_emission_signature_author,
        "emitterEmissionSignatureDate"           as emitter_emission_signature_date,
        "isEmissionDirectTakenOver"              as is_emission_direct_taken_over,
        "isEmissionTakenOverWithSecretCode"      as is_emission_taken_over_with_secret_code,
        "transporterCompanyName"                 as transporter_company_name,
        "transporterCompanySiret"                as transporter_company_siret,
        "transporterCompanyAddress"              as transporter_company_address,
        "transporterCompanyPhone"                as transporter_company_phone,
        "transporterCompanyContact"              as transporter_company_contact,
        "transporterCompanyMail"                 as transporter_company_mail,
        "transporterRecepisseNumber"             as transporter_recepisse_number,
        "transporterRecepisseDepartment"         as transporter_recepisse_department,
        "transporterRecepisseValidityLimit"      as transporter_recepisse_validity_limit,
        "transporterAcceptationStatus"           as transporter_acceptation_status,
        "transporterWasteRefusalReason"          as transporter_waste_refusal_reason,
        "transporterTakenOverAt"                 as transporter_taken_over_at,
        "transporterWastePackagings"             as transporter_waste_packagings,
        "transporterCustomInfo"                  as transporter_custom_info,
        "handedOverToRecipientAt"                as handed_over_to_recipient_at,
        "transporterTransportSignatureAuthor"    as transporter_transport_signature_author,
        "transporterTransportSignatureDate"      as transporter_transport_signature_date,
        "destinationCompanyName"                 as destination_company_name,
        "destinationCompanySiret"                as destination_company_siret,
        "destinationCompanyAddress"              as destination_company_address,
        "destinationCompanyContact"              as destination_company_contact,
        "destinationCompanyPhone"                as destination_company_phone,
        "destinationCompanyMail"                 as destination_company_mail,
        "destinationWastePackagings"             as destination_waste_packagings,
        "destinationReceptionAcceptationStatus"  as destination_reception_acceptation_status,
        "destinationReceptionWasteRefusalReason" as destination_reception_waste_refusal_reason,
        "destinationCustomInfo"                  as destination_custom_info,
        "destinationReceptionDate"               as destination_reception_date,
        "destinationOperationDate"               as destination_operation_date,
        "destinationReceptionSignatureAuthor"    as destination_reception_signature_author,
        "destinationReceptionSignatureDate"      as destination_reception_signature_date,
        "destinationOperationSignatureDate"      as destination_operation_signature_date,
        "destinationOperationSignatureAuthor"    as destination_operation_signature_author,
        "emissionSignatoryId"                    as emission_signatory_id,
        "transportSignatoryId"                   as transport_signatory_id,
        "receptionSignatoryId"                   as reception_signatory_id,
        "operationSignatoryId"                   as operation_signatory_id,
        "groupedInId"                            as grouped_in_id,
        "transporterTransportMode"               as transporter_transport_mode,
        type,
        "emitterWasteWeightIsEstimate"           as emitter_waste_weight_is_estimate,
        "transporterWasteWeightIsEstimate"       as transporter_waste_weight_is_estimate,
        "ecoOrganismeName"                       as eco_organisme_name,
        "ecoOrganismeSiret"                      as eco_organisme_siret,
        "transporterTransportPlates"             as transporter_transport_plates,
        "identificationNumbers"                  as identification_numbers,
        "transporterCompanyVatNumber"            as transporter_company_vat_number,
        "synthesizedInId"                        as synthesized_in_id,
        "emittedByEcoOrganisme"                  as emitted_by_eco_organisme,
        "synthesisEmitterSirets"                 as synthesis_emitter_sirets,
        "transporterRecepisseIsExempted"         as transporter_recepisse_is_exempted,
        "groupingEmitterSirets"                  as grouping_emitter_sirets,
        "destinationOperationMode"               as destination_operation_mode,
        "emitterWasteWeightValue"
        / 1000                                   as emitter_waste_weight_value,
        "emitterWasteVolume"
        / 1000                                   as emitter_waste_volume,
        "transporterWasteRefusedWeightValue"
        / 1000                                   as transporter_waste_refused_weight_value,
        "transporterWasteWeightValue"
        / 1000                                   as transporter_waste_weight_value,
        "transporterWasteVolume"
        / 1000                                   as transporter_waste_volume,
        "destinationReceptionWasteRefusedWeightValue"
        / 1000                                   as destination_reception_waste_refused_weight_value,
        "destinationReceptionWasteWeightValue"
        / 1000                                   as destination_reception_waste_weight_value,
        "destinationReceptionWasteVolume"
        / 1000                                   as destination_reception_waste_volume,
        replace(
            "destinationOperationCode", ' ', ''
        )                                        as destination_operation_code
    from
        source
)

select
    id,
    status,
    created_at,
    updated_at,
    is_deleted,
    is_draft,
    emitter_company_name,
    emitter_company_siret,
    emitter_company_address,
    emitter_company_contact,
    emitter_company_phone,
    emitter_company_mail,
    emitter_pickup_site_name,
    emitter_pickup_site_address,
    emitter_pickup_site_city,
    emitter_pickup_site_postal_code,
    emitter_pickup_site_infos,
    waste_code,
    waste_adr,
    emitter_waste_weight_value,
    emitter_waste_volume,
    emitter_waste_packagings,
    emitter_custom_info,
    emitter_emission_signature_author,
    emitter_emission_signature_date,
    is_emission_direct_taken_over,
    is_emission_taken_over_with_secret_code,
    transporter_company_name,
    transporter_company_siret,
    transporter_company_address,
    transporter_company_phone,
    transporter_company_contact,
    transporter_company_mail,
    transporter_recepisse_number,
    transporter_recepisse_department,
    transporter_recepisse_validity_limit,
    transporter_acceptation_status,
    transporter_waste_refusal_reason,
    transporter_waste_refused_weight_value,
    transporter_taken_over_at,
    transporter_waste_packagings,
    transporter_waste_weight_value,
    transporter_waste_volume,
    transporter_custom_info,
    handed_over_to_recipient_at,
    transporter_transport_signature_author,
    transporter_transport_signature_date,
    destination_company_name,
    destination_company_siret,
    destination_company_address,
    destination_company_contact,
    destination_company_phone,
    destination_company_mail,
    destination_waste_packagings,
    destination_reception_acceptation_status,
    destination_reception_waste_refusal_reason,
    destination_reception_waste_refused_weight_value,
    destination_reception_waste_weight_value,
    destination_reception_waste_volume,
    destination_custom_info,
    destination_reception_date,
    destination_operation_code,
    destination_operation_date,
    destination_reception_signature_author,
    destination_reception_signature_date,
    destination_operation_signature_date,
    destination_operation_signature_author,
    emission_signatory_id,
    transport_signatory_id,
    reception_signatory_id,
    operation_signatory_id,
    grouped_in_id,
    transporter_transport_mode,
    type,
    emitter_waste_weight_is_estimate,
    transporter_waste_weight_is_estimate,
    eco_organisme_name,
    eco_organisme_siret,
    transporter_transport_plates,
    identification_numbers,
    transporter_company_vat_number,
    synthesized_in_id,
    emitted_by_eco_organisme,
    synthesis_emitter_sirets,
    transporter_recepisse_is_exempted,
    grouping_emitter_sirets,
    destination_operation_mode
from renamed
