{{ config(
  pre_hook = "{{ create_indexes_for_source(['createdat','updatedat','emittercompanysiret','transportercompanysiret','destinationcompanysiret']) }}"
) }}
SELECT
    id                                                      AS "id",
    createdat                                               AS "created_at",
    updatedat                                               AS "updated_at",
    status                                                  AS "status",
    "type",
    isdeleted                                               AS "is_deleted",
    isdraft                                                 AS "is_draft",
    wastecode                                               AS "waste_code",
    wastefamilycode                                         AS "waste_family_code",
    wastepop                                                AS "waste_pop",
    wasteconsistence                                        AS "waste_consistence",
    wastematerialname                                       AS "waste_material_name",
    wasteadr                                                AS "waste_adr",
    wastesealnumbers                                        AS "waste_seal_numbers",
    weightisestimate                                        AS "weight_is_estimate",
    -- Passage en tonnes
    packagings                                              AS "packagings",
    repackagedinid                                          AS "repackaged_in_id",
    emittercompanysiret                                     AS "emitter_company_siret",
    emittercompanyname                                      AS "emitter_company_name",
    emittercompanyaddress                                   AS "emitter_company_address",
    emittercompanycontact                                   AS "emitter_company_contact",
    emittercompanymail                                      AS "emitter_company_mail",
    emittercompanyphone                                     AS "emitter_company_phone",
    emittercustominfo                                       AS "emitter_custom_info",
    emitteremissionsignatureauthor                          AS "emitter_emission_signature_author",
    emitteremissionsignaturedate                            AS "emitter_emission_signature_date",
    emitterisprivateindividual                              AS "emitter_isprivate_individual",
    emitterpickupsitename                                   AS "emitter_pickup_site_name",
    emitterpickupsiteaddress                                AS "emitter_pickup_site_address",
    emitterpickupsitepostalcode                             AS "emitter_pickup_site_postal_code",
    emitterpickupsitecity                                   AS "emitter_pickup_site_city",
    emitterpickupsiteinfos                                  AS "emitter_pickup_site_infos",
    workercompanysiret                                      AS "worker_company_siret",
    workercompanyname                                       AS "worker_company_name",
    workercompanyaddress                                    AS "worker_company_address",
    workercompanycontact                                    AS "worker_company_contact",
    workercompanyphone                                      AS "worker_company_phone",
    workercompanymail                                       AS "worker_company_mail",
    workercertificationorganisation                         AS "worker_certification_organisation",
    workercertificationcertificationnumber                  AS "worker_certification_certification_number",
    workercertificationhassubsectionthree                   AS "worker_certification_has_subsection_three",
    workercertificationhassubsectionfour                    AS "worker_certification_has_subsection_four",
    workercertificationvaliditylimit                        AS "worker_certificationvalidity_limit",
    workerworkhasemitterpapersignature                      AS "worker_work_has_emitter_paper_signature",
    workerworksignatureauthor                               AS "worker_work_signature_author",
    workerworksignaturedate                                 AS "worker_work_signature_date",
    workerisdisabled                                        AS "worker_is_disabled",
    transportercompanysiret                                 AS "transporter_company_siret",
    transportercompanyname                                  AS "transporter_company_name",
    transportercompanyaddress                               AS "transporter_company_address",
    transporterrecepissedepartment                          AS "transporter_recepisse_department",
    transportercompanycontact                               AS "transporter_company_contact",
    transportercompanymail                                  AS "transporter_company_mail",
    transportercompanyphone                                 AS "transporter_company_phone",
    transportercompanyvatnumber                             AS "transporter_company_vat_number",
    transportercustominfo                                   AS "transporter_custom_info",
    transporterrecepisseisexempted                          AS "transporter_recepisse_is_exempted",
    transporterrecepissenumber                              AS "transporter_recepisse_number",
    transporterrecepissevaliditylimit                       AS "transporter_recepisse_validity_limit",
    transportertransportmode                                AS "transporter_transport_mode",
    transportertransportplates                              AS "transporter_transport_plates",
    transportertransportsignatureauthor                     AS "transporter_transport_signature_author",
    transportertransportsignaturedate                       AS "transporter_transport_signature_date",
    transportertransporttakenoverat                         AS "transporter_transport_taken_over_at",
    destinationcompanysiret                                 AS "destination_company_siret",
    destinationcompanyname                                  AS "destination_company_name",
    destinationcompanyaddress                               AS "destination_company_address",
    destinationcompanycontact                               AS "destination_company_contact",
    destinationcompanymail                                  AS "destination_company_mail",
    destinationcompanyphone                                 AS "destination_company_phone",
    destinationcustominfo                                   AS "destination_custom_info",
    destinationreceptiondate                                AS "destination_reception_date",
    destinationcap                                          AS "destination_cap",
    destinationreceptionacceptationstatus                   AS "destination_reception_acceptation_status",
    destinationoperationdate                                AS "destination_operation_date",
    destinationoperationdescription                         AS "destination_operation_description",
    destinationoperationsignatureauthor                     AS "destination_operation_signature_author",
    destinationoperationsignaturedate                       AS "destination_operation_signature_date",
    destinationreceptionrefusalreason                       AS "destination_reception_refusal_reason",
    ecoorganismesiret                                       AS "eco_organisme_siret",
    ecoorganismename                                        AS "eco_organisme_name",
    destinationoperationnextdestinationcompanysiret         AS "destination_operation_next_destination_company_siret",
    -- Passage en tonnes
    destinationoperationnextdestinationcompanyname          AS "destination_operation_next_destination_company_name",
    destinationoperationnextdestinationcompanyaddress       AS "destination_operation_next_destination_company_address",
    destinationoperationnextdestinationcompanycontact       AS "destination_operation_next_destination_company_contact",
    destinationoperationnextdestinationcompanymail          AS "destination_operation_next_destination_company_mail",
    destinationoperationnextdestinationcompanyphone         AS "destination_operation_next_destination_company_phone",
    destinationoperationnextdestinationcompanyvatnumber     AS "destination_operation_next_destination_company_vat_number",
    destinationoperationnextdestinationcap                  AS "destination_operation_next_destination_cap",
    destinationoperationnextdestinationplannedoperationcode AS "destination_operation_next_destination_planned_operation_code",
    brokercompanyaddress                                    AS "broker_company_address",
    brokercompanycontact                                    AS "broker_company_contact",
    brokercompanymail                                       AS "broker_company_mail",
    brokercompanyname                                       AS "broker_company_name",
    brokercompanyphone                                      AS "broker_company_phone",
    brokercompanysiret                                      AS "broker_company_siret",
    brokerrecepissedepartment                               AS "broker_recepisse_department",
    brokerrecepissenumber                                   AS "broker_recepisse_number",
    brokerrecepissevaliditylimit                            AS "broker_recepisse_validity_limit",
    forwardingid                                            AS "forwarding_id",
    groupedinid                                             AS "grouped_in_id",
    replace(
        destinationplannedoperationcode, ' ', ''
    )                                                       AS "destination_planned_operation_code",
    replace(
        destinationoperationcode, ' ', ''
    )                                                       AS "destination_operation_code",
    weightvalue / 1000                                      AS "weight_value",
    destinationreceptionweight
    / 1000                                                  AS "destination_reception_weight"
FROM
    {{ source("raw_zone_trackdechets", "bsda_raw") }}
