{{ config(
  pre_hook = "{{ create_indexes_for_source(['createdat','updatedat','emittercompanysiret','transportercompanysiret','destinationcompanysiret']) }}"
) }}
SELECT
    id                                     AS "id",
    createdat                              AS "created_at",
    updatedat                              AS "updated_at",
    status                                 AS "status",
    "type",
    isdeleted                              AS "is_deleted",
    isdraft                                AS "is_draft",
    wasteadr                               AS "waste_adr",
    wastecode                              AS "waste_code",
    identificationnumbers                  AS "identification_numbers",
    emittercompanysiret                    AS "emitter_company_siret",
    emittercompanyname                     AS "emitter_company_name",
    emittercompanyaddress                  AS "emitter_company_address",
    emittercompanycontact                  AS "emitter_company_contact",
    emittercompanymail                     AS "emitter_company_mail",
    emittercompanyphone                    AS "emitter_company_phone",
    emittercustominfo                      AS "emitter_custom_info",
    emitterpickupsitename                  AS "emitter_pickup_sitename",
    emitterpickupsiteaddress               AS "emitter_pickup_site_address",
    emitterpickupsitepostalcode            AS "emitter_pickup_site_postal_code",
    emitterpickupsitecity                  AS "emitter_pickup_site_city",
    emitterpickupsiteinfos                 AS "emitter_pickup_site_infos",
    emitteremissionsignaturedate           AS "emitter_emission_signature_date",
    emitteremissionsignatureauthor         AS "emitter_emission_signature_author",
    emittedbyecoorganisme                  AS "emitted_by_eco_organisme",
    emitterwasteweightvalue                AS "emitter_waste_weight_value",
    emitterwasteweightisestimate           AS "emitter_waste_weight_is_estimate",
    emitterwastepackagings                 AS "emitter_waste_packagings",
    emissionsignatoryid                    AS "emission_signatory_id",
    isemissiondirecttakenover              AS "is_emission_direct_taken_over",
    isemissiontakenoverwithsecretcode      AS "is_emission_taken_over_with_secret_code",
    transportercompanysiret                AS "transporter_company_siret",
    transportercompanyname                 AS "transporter_company_name",
    transportercompanyaddress              AS "transporter_company_address",
    transportercompanycontact              AS "transporter_company_contact",
    transportercompanymail                 AS "transporter_company_mail",
    transportercompanyphone                AS "transporter_company_phone",
    transportercompanyvatnumber            AS "transporter_company_vat_number",
    transportercustominfo                  AS "transporter_custom_info",
    transportsignatoryid                   AS "transport_signatory_id",
    transporterrecepissenumber             AS "transporter_recepisse_number",
    transporterrecepissedepartment         AS "transporter_recepisse_department",
    transporterrecepissevaliditylimit      AS "transporter_recepisse_validity_limit",
    transportertransportmode               AS "transporter_transport_mode",
    transportertransportplates             AS "transporter_transport_plates",
    transporteracceptationstatus           AS "transporter_acceptation_status",
    transportertakenoverat                 AS "transporter_taken_over_at",
    transportertransportsignaturedate      AS "transporter_transport_signature_date",
    transportertransportsignatureauthor    AS "transporter_transport_signature_author",
    transporterwasteweightisestimate       AS "transporter_waste_weight_is_estimate",
    transporterwastepackagings             AS "transporter_waste_packagings",
    transporterwasterefusalreason          AS "transporter_waste_refusal_reason",
    transporterwasterefusedweightvalue     AS "transporter_waste_refused_weight_value",
    destinationcompanysiret                AS "destination_company_siret",
    destinationcompanyname                 AS "destination_company_name",
    destinationcompanyaddress              AS "destination_company_address",
    destinationcompanycontact              AS "destination_company_contact",
    destinationcompanymail                 AS "destination_company_mail",
    destinationcompanyphone                AS "destination_company_phone",
    destinationcustominfo                  AS "destination_custom_info",
    destinationreceptiondate               AS "destination_reception_date",
    destinationreceptionsignaturedate      AS "destination_reception_signature_date",
    destinationreceptionsignatureauthor    AS "destination_reception_signature_author",
    destinationwastepackagings             AS "destination_waste_packagings",
    destinationreceptionwasterefusalreason AS "destination_reception_waste_refusal_reason",
    receptionsignatoryid                   AS "reception_signatory_id",
    destinationoperationdate               AS "destination_operation_date",
    destinationoperationcode               AS "destination_operation_code",
    destinationoperationsignaturedate      AS "destination_operation_signature_date",
    destinationoperationsignatureauthor    AS "destination_operation_signature_author",
    operationsignatoryid                   AS "operation_signatory_id",
    destinationreceptionacceptationstatus  AS "destination_reception_acceptation_status",
    handedovertorecipientat                AS "handed_over_to_recipient_at",
    ecoorganismesiret                      AS "eco_organisme_siret",
    ecoorganismename                       AS "eco_organisme_name",
    groupedinid                            AS "grouped_in_id",
    synthesizedinid                        AS "synthesized_in_id",
    emitterwastevolume / 1000              AS "emitter_waste_volume",
    transporterwastevolume / 1000          AS "transporter_waste_volume",
    destinationreceptionwastevolume
    / 1000                                 AS "destination_reception_waste_volume",
    transporterwasteweightvalue / 1000     AS "transporter_waste_weight_value",
    destinationreceptionwasteweightvalue
    / 1000                                 AS "destination_reception_waste_weight_value",
    destinationreceptionwasterefusedweightvalue
    / 1000                                 AS "destination_reception_waste_refused_weight_value"
FROM
    {{ source("raw_zone_trackdechets", "bsdasri_raw") }}
