SELECT
    id as id,
    createdat as created_at,
    updatedat as updated_at,
    bsdaid as bsda_id,
    authoringcompanyid as authoring_company_id,
    "comment" as "comment",
    "status" as "status",
    wastecode as waste_code,
    wastepop as waste_pop,
    packagings as packagings,
    wastesealnumbers as waste_seal_numbers,
    wastematerialname as waste_material_name,
    destinationcap as destination_cap,
    destinationreceptionweight as destination_reception_weight,
    destinationoperationcode as destination_operation_code,
    destinationoperationdescription as destination_operation_description,
    brokercompanysiret as broker_company_siret,
    brokercompanyname as broker_company_name,
    brokercompanyaddress as broker_company_address,
    brokercompanycontact as broker_company_contact,
    brokercompanymail as broker_company_mail,
    brokercompanyphone as broker_company_phone,
    brokerrecepissenumber as broker_recepisse_number,
    brokerrecepissevaliditylimit as broker_recepisse_validity_limit,
    brokerrecepissedepartment as broker_recepisse_department,
    emitterpickupsitename as emitter_pickup_sitename,
    emitterpickupsiteaddress as emitter_pickup_site_address,
    emitterpickupsitecity as emitter_pickup_site_city,
    emitterpickupsitepostalcode as emitter_pickup_site_postal_code,
    emitterpickupsiteinfos as emitter_pickup_site_infos
FROM
    {{ source('raw_zone_trackdechets', 'bsda_revision_request_raw') }}