{{ config(
  pre_hook = "{{ create_indexes_for_source([
    'createdAt',
    'updatedAt',
    'emitterCompanySiret',
    'destinationCompanySiret',
    'workerCompanySiret',
    'wasteCode',
    'wastePop',
    'ecoOrganismeSiret',
    'transporterTransportSignatureDate',
    'destinationOperationDate'
  ]) }}"
) }}

with source as (
    select * from {{ source('raw_zone_trackdechets', 'bsda_raw') }}
),

renamed as (
    select
        id,
        "createdAt"                                           as created_at,
        "updatedAt"                                           as updated_at,
        "isDraft"                                             as is_draft,
        "isDeleted"                                           as is_deleted,
        status,
        "type",
        "emitterIsPrivateIndividual"                          as emitter_is_private_individual,
        "emitterCompanyName"                                  as emitter_company_name,
        "emitterCompanySiret"                                 as emitter_company_siret,
        "emitterCompanyAddress"                               as emitter_company_address,
        "emitterCompanyContact"                               as emitter_company_contact,
        "emitterCompanyPhone"                                 as emitter_company_phone,
        "emitterCompanyMail"                                  as emitter_company_mail,
        "emitterPickupSiteName"                               as emitter_pickup_site_name,
        "emitterPickupSiteAddress"                            as emitter_pickup_site_address,
        "emitterPickupSiteCity"                               as emitter_pickup_site_city,
        "emitterPickupSitePostalCode"                         as emitter_pickup_site_postal_code,
        "emitterPickupSiteInfos"                              as emitter_pickup_site_infos,
        "emitterEmissionSignatureAuthor"                      as emitter_emission_signature_author,
        cast(
            "emitterEmissionSignatureDate" as timestamptz
        )                                                     as emitter_emission_signature_date,
        "wasteCode"                                           as waste_code,
        "wasteFamilyCode"                                     as waste_family_code,
        "wasteMaterialName"                                   as waste_material_name,
        "wasteConsistence"                                    as waste_consistence,
        "wasteSealNumbers"                                    as waste_seal_numbers,
        "wasteAdr"                                            as waste_adr,
        packagings,
        "destinationCompanyName"                              as destination_company_name,
        "destinationCompanySiret"                             as destination_company_siret,
        "destinationCompanyAddress"                           as destination_company_address,
        "destinationCompanyContact"                           as destination_company_contact,
        "destinationCompanyPhone"                             as destination_company_phone,
        "destinationCompanyMail"                              as destination_company_mail,
        "destinationCap"                                      as destination_cap,
        "destinationReceptionDate"                            as destination_reception_date,
        "destinationReceptionAcceptationStatus"               as destination_reception_acceptation_status,
        "destinationReceptionRefusalReason"                   as destination_reception_refusal_reason,
        "destinationOperationDate"                            as destination_operation_date,
        "destinationOperationSignatureAuthor"                 as destination_operation_signature_author,
        "destinationOperationSignatureDate"                   as destination_operation_signature_date,
        cast(
            "transporterTransportSignatureDate" as timestamptz
        )                                                     as transporter_transport_signature_date,
        "workerCompanyName"                                   as worker_company_name,
        "workerCompanySiret"                                  as worker_company_siret,
        "workerCompanyAddress"                                as worker_company_address,
        "workerCompanyContact"                                as worker_company_contact,
        "workerCompanyPhone"                                  as worker_company_phone,
        "workerCompanyMail"                                   as worker_company_mail,
        "workerWorkHasEmitterPaperSignature"                  as worker_work_has_emitter_paper_signature,
        "workerWorkSignatureAuthor"                           as worker_work_signature_author,
        "workerWorkSignatureDate"                             as worker_work_signature_date,
        "brokerCompanyName"                                   as broker_company_name,
        "brokerCompanySiret"                                  as broker_company_siret,
        "brokerCompanyAddress"                                as broker_company_address,
        "brokerCompanyContact"                                as broker_company_contact,
        "brokerCompanyPhone"                                  as broker_company_phone,
        "brokerCompanyMail"                                   as broker_company_mail,
        "brokerRecepisseNumber"                               as broker_recepisse_number,
        "brokerRecepisseDepartment"                           as broker_recepisse_department,
        cast(
            "brokerRecepisseValidityLimit" as timestamptz
        )                                                     as broker_recepisse_validity_limit,
        "destinationOperationNextDestinationCompanyName"      as destination_operation_next_destination_company_name,
        "destinationOperationNextDestinationCompanySiret"     as destination_operation_next_destination_company_siret,
        "destinationOperationNextDestinationCompanyVatNumber" as destination_operation_next_destination_company_vat_number,
        "destinationOperationNextDestinationCompanyAddress"   as destination_operation_next_destination_company_address,
        "destinationOperationNextDestinationCompanyContact"   as destination_operation_next_destination_company_contact,
        "destinationOperationNextDestinationCompanyPhone"     as destination_operation_next_destination_company_phone,
        "destinationOperationNextDestinationCompanyMail"      as destination_operation_next_destination_company_mail,
        "destinationOperationNextDestinationCap"              as destination_operation_next_destination_cap,
        "weightIsEstimate"                                    as weight_is_estimate,
        "emitterCustomInfo"                                   as emitter_custom_info,
        "destinationCustomInfo"                               as destination_custom_info,
        "ecoOrganismeName"                                    as eco_organisme_name,
        "ecoOrganismeSiret"                                   as eco_organisme_siret,
        "forwardingId"                                        as forwarding_id,
        "groupedInId"                                         as grouped_in_id,
        "wastePop"                                            as waste_pop,
        "destinationOperationDescription"                     as destination_operation_description,
        "workerIsDisabled"                                    as worker_is_disabled,
        "workerCertificationHasSubSectionFour"                as worker_certification_has_sub_section_four,
        "workerCertificationHasSubSectionThree"               as worker_certification_has_sub_section_three,
        "workerCertificationCertificationNumber"              as worker_certification_certification_number,
        "workerCertificationValidityLimit"                    as worker_certification_validity_limit,
        "workerCertificationOrganisation"                     as worker_certification_organisation,
        "intermediariesOrgIds"                                as intermediaries_org_ids,
        "destinationOperationMode"                            as destination_operation_mode,
        "transportersOrgIds"                                  as transporters_org_ids,
        "weightValue"
        / 1000                                                as weight_value,
        replace(
            "destinationPlannedOperationCode", ' ', ''
        )                                                     as destination_planned_operation_code,
        "destinationReceptionWeight"
        / 1000                                                as destination_reception_weight,
        replace(
            "destinationOperationCode", ' ', ''
        )                                                     as destination_operation_code,
        replace(
            "destinationOperationNextDestinationPlannedOperationCode", ' ', ''
        )                                                     as destination_operation_next_destination_planned_operation_code
    from
        source
)

select
    id,
    created_at,
    updated_at,
    is_draft,
    is_deleted,
    status,
    type,
    emitter_is_private_individual,
    emitter_company_name,
    emitter_company_siret,
    emitter_company_address,
    emitter_company_contact,
    emitter_company_phone,
    emitter_company_mail,
    emitter_pickup_site_name,
    emitter_pickup_site_address,
    emitter_pickup_site_city,
    emitter_pickup_site_postal_code,
    emitter_pickup_site_infos,
    emitter_emission_signature_author,
    emitter_emission_signature_date,
    waste_code,
    waste_family_code,
    waste_material_name,
    waste_consistence,
    waste_seal_numbers,
    waste_adr,
    packagings,
    weight_value,
    destination_company_name,
    destination_company_siret,
    destination_company_address,
    destination_company_contact,
    destination_company_phone,
    destination_company_mail,
    destination_cap,
    destination_planned_operation_code,
    destination_reception_date,
    destination_reception_weight,
    destination_reception_acceptation_status,
    destination_reception_refusal_reason,
    destination_operation_code,
    destination_operation_date,
    destination_operation_signature_author,
    destination_operation_signature_date,
    transporter_transport_signature_date,
    worker_company_name,
    worker_company_siret,
    worker_company_address,
    worker_company_contact,
    worker_company_phone,
    worker_company_mail,
    worker_work_has_emitter_paper_signature,
    worker_work_signature_author,
    worker_work_signature_date,
    broker_company_name,
    broker_company_siret,
    broker_company_address,
    broker_company_contact,
    broker_company_phone,
    broker_company_mail,
    broker_recepisse_number,
    broker_recepisse_department,
    broker_recepisse_validity_limit,
    destination_operation_next_destination_company_name,
    destination_operation_next_destination_company_siret,
    destination_operation_next_destination_company_vat_number,
    destination_operation_next_destination_company_address,
    destination_operation_next_destination_company_contact,
    destination_operation_next_destination_company_phone,
    destination_operation_next_destination_company_mail,
    destination_operation_next_destination_cap,
    destination_operation_next_destination_planned_operation_code,
    weight_is_estimate,
    emitter_custom_info,
    destination_custom_info,
    eco_organisme_name,
    eco_organisme_siret,
    forwarding_id,
    grouped_in_id,
    waste_pop,
    destination_operation_description,
    worker_is_disabled,
    worker_certification_has_sub_section_four,
    worker_certification_has_sub_section_three,
    worker_certification_certification_number,
    worker_certification_validity_limit,
    worker_certification_organisation,
    intermediaries_org_ids,
    destination_operation_mode,
    transporters_org_ids
from renamed
