SELECT
    id,
    "bsffid" as bsff_id,
    numero,
    "type",
    volume,
    weight/1000 as "weight",
    "acceptationstatus" as acceptation_status,
    "acceptationdate" as acceptation_date,
    "acceptationsignaturedate" as acceptation_signature_date,
    "acceptationsignatureauthor" as acceptation_signature_author,
    "acceptationrefusalreason" as acceptationRefusalReason,
    "acceptationweight" as acceptation_weight,
    "acceptationwastecode" as acceptation_waste_code,
    "acceptationwastedescription" as acceptation_waste_description,
    "operationdate" as operation_date,
    "operationsignaturedate" as operation_signature_date,
    "operationsignatureauthor" as operation_signature_author,
    "operationcode" as operation_code,
    "operationdescription" as operation_description,
    "operationnotraceability" as operation_no_traceability,
    "operationnextdestinationcompanysiret" as operation_next_destination_company_siret,
    "operationnextdestinationcompanyvatnumber" as operation_next_destination_company_vat_number,
    "operationnextdestinationcompanyname" as operation_next_destination_company_name,
    "operationnextdestinationcompanyaddress" as operation_next_destination_company_address,
    "operationnextdestinationcompanycontact" as operation_next_destination_company_contact,
    "operationnextdestinationcompanymail" as operation_next_destination_company_mail,
    "operationnextdestinationcompanyphone" as operation_next_destination_company_phone,
    "operationnextdestinationplannedoperationcode" as operation_next_destination_planned_operation_code,
    "operationnextdestinationcap" as operation_next_destination_cap,
    "nextpackagingid" as next_packaging_id,
    other
FROM
    {{ source('raw_zone_trackdechets', 'bsff_packaging_raw') }}
