{{ config(
  pre_hook = "{{ create_indexes_for_source(['createdAt','updatedAt','emitterCompanySiret','transporterCompanySiret','destinationCompanySiret']) }}"
) }}
with source as (
    select *
    from {{ source('raw_zone_trackdechets', 'bsff_raw') }}
),

renamed as (
    select
        id,
        "createdAt"                           as created_at,
        "updatedAt"                           as updated_at,
        "isDeleted"                           as is_deleted,
        "emitterCompanyName"                  as emitter_company_name,
        "emitterCompanySiret"                 as emitter_company_siret,
        "emitterCompanyAddress"               as emitter_company_address,
        "emitterCompanyContact"               as emitter_company_contact,
        "emitterCompanyPhone"                 as emitter_company_phone,
        "emitterCompanyMail"                  as emitter_company_mail,
        "emitterEmissionSignatureAuthor"      as emitter_emission_signature_author,
        "emitterEmissionSignatureDate"        as emitter_emission_signature_date,
        "wasteCode"                           as waste_code,
        "wasteAdr"                            as waste_adr,
        "weightIsEstimate"                    as weight_is_estimate,
        "transporterCompanyName"              as transporter_company_name,
        "transporterCompanySiret"             as transporter_company_siret,
        "transporterCompanyAddress"           as transporter_company_address,
        "transporterCompanyContact"           as transporter_company_contact,
        "transporterCompanyPhone"             as transporter_company_phone,
        "transporterCompanyMail"              as transporter_company_mail,
        "transporterRecepisseNumber"          as transporter_recepisse_number,
        "transporterRecepisseDepartment"      as transporter_recepisse_department,
        "transporterRecepisseValidityLimit"   as transporter_recepisse_validity_limit,
        "transporterTransportMode"            as transporter_transport_mode,
        "transporterTransportSignatureAuthor" as transporter_transport_signature_author,
        "transporterTransportSignatureDate"   as transporter_transport_signature_date,
        "destinationCompanyName"              as destination_company_name,
        "destinationCompanySiret"             as destination_company_siret,
        "destinationCompanyAddress"           as destination_company_address,
        "destinationCompanyContact"           as destination_company_contact,
        "destinationCompanyPhone"             as destination_company_phone,
        "destinationCompanyMail"              as destination_company_mail,
        "destinationReceptionDate"            as destination_reception_date,
        "destinationReceptionSignatureAuthor" as destination_reception_signature_author,
        "destinationReceptionSignatureDate"   as destination_reception_signature_date,
        "transporterCompanyVatNumber"         as transporter_company_vat_number,
        status,
        "wasteDescription"                    as waste_description,
        "isDraft"                             as is_draft,
        "type",
        "destinationCustomInfo"               as destination_custom_info,
        "emitterCustomInfo"                   as emitter_custom_info,
        "transporterCustomInfo"               as transporter_custom_info,
        cast(
            "transporterTransportTakenOverAt" as timestamptz
        )                                     as transporter_transport_taken_over_at,
        "transporterTransportPlates"          as transporter_transport_plates,
        "destinationCap"                      as destination_cap,
        "detenteurCompanySirets"              as detenteur_company_sirets,
        "transporterRecepisseIsExempted"      as transporter_recepisse_is_exempted,
        "weightValue" / 1000                  as weight_value,
        replace(
            "destinationPlannedOperationCode", ' ', ''
        )                                     as destination_planned_operation_code
    from
        source
)

select
    id,
    created_at,
    updated_at,
    is_deleted,
    emitter_company_name,
    emitter_company_siret,
    emitter_company_address,
    emitter_company_contact,
    emitter_company_phone,
    emitter_company_mail,
    emitter_emission_signature_author,
    emitter_emission_signature_date,
    waste_code,
    waste_adr,
    weight_value,
    weight_is_estimate,
    transporter_company_name,
    transporter_company_siret,
    transporter_company_address,
    transporter_company_contact,
    transporter_company_phone,
    transporter_company_mail,
    transporter_recepisse_number,
    transporter_recepisse_department,
    transporter_recepisse_validity_limit,
    transporter_transport_mode,
    transporter_transport_signature_author,
    transporter_transport_signature_date,
    destination_company_name,
    destination_company_siret,
    destination_company_address,
    destination_company_contact,
    destination_company_phone,
    destination_company_mail,
    destination_reception_date,
    destination_reception_signature_author,
    destination_reception_signature_date,
    destination_planned_operation_code,
    transporter_company_vat_number,
    status,
    waste_description,
    is_draft,
    "type",
    destination_custom_info,
    emitter_custom_info,
    transporter_custom_info,
    transporter_transport_taken_over_at,
    transporter_transport_plates,
    destination_cap,
    detenteur_company_sirets,
    transporter_recepisse_is_exempted
from renamed
