{{ config(
  pre_hook = "{{ create_indexes_for_source([
    'createdAt',
    'updatedAt',
    'emitterCompanySiret',
    'transporterCompanySiret',
    'destinationCompanySiret',
    'wasteCode'
    ]) }}"
) }}
with source as (
    select *
    from {{ source('raw_zone_trackdechets', 'bsvhu_raw') }}
),

renamed as (
    select
        id,
        "createdAt"                                           as created_at,
        "updatedAt"                                           as updated_at,
        "isDraft"                                             as is_draft,
        "isDeleted"                                           as is_deleted,
        status,
        "emitterAgrementNumber"                               as emitter_agrement_number,
        "emitterCompanyName"                                  as emitter_company_name,
        "emitterCompanySiret"                                 as emitter_company_siret,
        "emitterCompanyAddress"                               as emitter_company_address,
        "emitterCompanyContact"                               as emitter_company_contact,
        "emitterCompanyPhone"                                 as emitter_company_phone,
        "emitterCompanyMail"                                  as emitter_company_mail,
        "destinationType"                                     as destination_type,
        "destinationAgrementNumber"                           as destination_agrement_number,
        "destinationCompanyName"                              as destination_company_name,
        "destinationCompanySiret"                             as destination_company_siret,
        "destinationCompanyAddress"                           as destination_company_address,
        "destinationCompanyContact"                           as destination_company_contact,
        "destinationCompanyPhone"                             as destination_company_phone,
        "destinationCompanyMail"                              as destination_company_mail,
        "wasteCode"                                           as waste_code,
        packaging,
        "identificationNumbers"                               as identification_numbers,
        "identificationType"                                  as identification_type,
        quantity,
        "emitterEmissionSignatureAuthor"                      as emitter_emission_signature_author,
        "emitterEmissionSignatureDate"                        as emitter_emission_signature_date,
        "transporterCompanyName"                              as transporter_company_name,
        "transporterCompanySiret"                             as transporter_company_siret,
        "transporterCompanyAddress"                           as transporter_company_address,
        "transporterCompanyContact"                           as transporter_company_contact,
        "transporterCompanyPhone"                             as transporter_company_phone,
        "transporterCompanyMail"                              as transporter_company_mail,
        "transporterRecepisseNumber"                          as transporter_recepisse_number,
        "transporterRecepisseDepartment"                      as transporter_recepisse_department,
        cast(
            "transporterRecepisseValidityLimit" as timestamptz
        )                                                     as transporter_recepisse_validity_limit,
        "transporterCompanyVatNumber"                         as transporter_company_vat_number,
        "transporterTransportSignatureAuthor"                 as transporter_transport_signature_author,
        "transporterTransportSignatureDate"                   as transporter_transport_signature_date,
        "destinationReceptionAcceptationStatus"               as destination_reception_acceptation_status,
        "destinationReceptionRefusalReason"                   as destination_reception_refusal_reason,
        "destinationReceptionIdentificationNumbers"           as destination_reception_identification_numbers,
        "destinationReceptionIdentificationType"              as destination_reception_identification_type,
        "destinationOperationNextDestinationCompanyName"      as destination_operation_next_destination_company_name,
        "destinationOperationNextDestinationCompanySiret"     as destination_operation_next_destination_company_siret,
        "destinationOperationNextDestinationCompanyAddress"   as destination_operation_next_destination_company_address,
        "destinationOperationNextDestinationCompanyContact"   as destination_operation_next_destination_company_contact,
        "destinationOperationNextDestinationCompanyPhone"     as destination_operation_next_destination_company_phone,
        "destinationOperationNextDestinationCompanyMail"      as destination_operation_next_destination_company_mail,
        "destinationOperationSignatureAuthor"                 as destination_operation_signature_author,
        "destinationOperationSignatureDate"                   as destination_operation_signature_date,
        "transporterTransportTakenOverAt"                     as transporter_transport_taken_over_at,
        cast(
            "destinationOperationDate" as timestamptz
        )                                                     as destination_operation_date,
        "destinationReceptionQuantity"                        as destination_reception_quantity,
        "destinationReceptionDate"                            as destination_reception_date,
        "weightIsEstimate"                                    as weight_is_estimate,
        "destinationOperationNextDestinationCompanyVatNumber" as destination_operation_next_destination_company_vat_number,
        "emitterCustomInfo"                                   as emitter_custom_info,
        "destinationCustomInfo"                               as destination_custom_info,
        "transporterCustomInfo"                               as transporter_custom_info,
        "transporterTransportPlates"                          as transporter_transport_plates,
        "transporterRecepisseIsExempted"                      as transporter_recepisse_is_exempted,
        "destinationOperationMode"                            as destination_operation_mode,
        replace(
            "destinationPlannedOperationCode", ' ', ''
        )                                                     as destination_planned_operation_code,
        "weightValue"
        / 1000                                                as weight_value,
        replace(
            "destinationOperationCode", ' ', ''
        )                                                     as destination_operation_code,
        "destinationReceptionWeight"
        / 1000                                                as destination_reception_weight
    from
        source
)

select
    id,
    created_at,
    updated_at,
    is_draft,
    is_deleted,
    status,
    emitter_agrement_number,
    emitter_company_name,
    emitter_company_siret,
    emitter_company_address,
    emitter_company_contact,
    emitter_company_phone,
    emitter_company_mail,
    destination_type,
    destination_planned_operation_code,
    destination_agrement_number,
    destination_company_name,
    destination_company_siret,
    destination_company_address,
    destination_company_contact,
    destination_company_phone,
    destination_company_mail,
    waste_code,
    packaging,
    identification_numbers,
    identification_type,
    quantity,
    weight_value,
    emitter_emission_signature_author,
    emitter_emission_signature_date,
    transporter_company_name,
    transporter_company_siret,
    transporter_company_address,
    transporter_company_contact,
    transporter_company_phone,
    transporter_company_mail,
    transporter_recepisse_number,
    transporter_recepisse_department,
    transporter_recepisse_validity_limit,
    transporter_company_vat_number,
    transporter_transport_signature_author,
    transporter_transport_signature_date,
    destination_reception_acceptation_status,
    destination_reception_refusal_reason,
    destination_reception_identification_numbers,
    destination_reception_identification_type,
    destination_operation_code,
    destination_operation_next_destination_company_name,
    destination_operation_next_destination_company_siret,
    destination_operation_next_destination_company_address,
    destination_operation_next_destination_company_contact,
    destination_operation_next_destination_company_phone,
    destination_operation_next_destination_company_mail,
    destination_operation_signature_author,
    destination_operation_signature_date,
    transporter_transport_taken_over_at,
    destination_operation_date,
    destination_reception_quantity,
    destination_reception_weight,
    destination_reception_date,
    weight_is_estimate,
    destination_operation_next_destination_company_vat_number,
    emitter_custom_info,
    destination_custom_info,
    transporter_custom_info,
    transporter_transport_plates,
    transporter_recepisse_is_exempted,
    destination_operation_mode
from renamed
