{{ config(
  pre_hook = "{{ create_indexes_for_source(['createdat','emittercompanysiret','transportercompanysiret','destinationcompanysiret']) }}"
) }}
SELECT
    id                                                  AS "id",
    createdat                                           AS "created_at",
    updatedat                                           AS "updated_at",
    isdeleted                                           AS "is_deleted",
    isdraft                                             AS "is_draft",
    status                                              AS "status",
    wastecode                                           AS "waste_code",
    quantity                                            AS "quantity",
    -- Passage en tonnes
    weightisestimate                                    AS "weight_is_estimate",
    packaging                                           AS "packaging",
    emittercompanysiret                                 AS "emitter_company_siret",
    emittercompanyname                                  AS "emitter_company_name",
    emittercompanyaddress                               AS "emitter_company_address",
    emittercompanycontact                               AS "emitter_company_contact",
    emittercompanymail                                  AS "emitter_company_mail",
    emittercompanyphone                                 AS "emitter_company_phone",
    emittercustominfo                                   AS "emitter_custom_info",
    emitteragrementnumber                               AS "emitter_agrement_number",
    emitteremissionsignaturedate                        AS "emitter_emission_signature_date",
    emitteremissionsignatureauthor                      AS "emitter_emission_signature_author",
    transportercompanysiret                             AS "transporter_company_siret",
    transportercompanyname                              AS "transporter_company_name",
    transportercompanyaddress                           AS "transporter_company_address",
    transportercompanycontact                           AS "transporter_company_contact",
    transportercompanymail                              AS "transporter_company_mail",
    transportercompanyphone                             AS "transporter_company_phone",
    transportercustominfo                               AS "transporter_custom_info",
    transportercompanyvatnumber                         AS "transporter_company_vat_number",
    transporterrecepissenumber                          AS "transporter_recepisse_number",
    transporterrecepissedepartment                      AS "transporter_recepisse_department",
    transporterrecepissevaliditylimit                   AS "transporter_recepisse_validity_limit",
    transportertransportplates                          AS "transporter_transport_plates",
    transportertransporttakenoverat                     AS "transporter_transport_taken_over_at",
    transportertransportsignaturedate                   AS "transporter_transport_signature_date",
    transportertransportsignatureauthor                 AS "transporter_transport_signature_author",
    destinationcompanysiret                             AS "destination_company_siret",
    destinationcompanyname                              AS "destination_company_name",
    destinationcompanyaddress                           AS "destination_company_address",
    destinationcompanycontact                           AS "destination_company_contact",
    destinationcompanymail                              AS "destination_company_mail",
    destinationcompanyphone                             AS "destination_company_phone",
    destinationcustominfo                               AS "destination_custom_info",
    destinationagrementnumber                           AS "destination_agrement_number",
    destinationreceptiondate                            AS "destination_reception_date",
    destinationreceptionquantity                        AS "destination_reception_quantity",
    -- Passage en tonnes
    destinationreceptionidentificationnumbers           AS "destination_reception_identification_numbers",
    destinationreceptionidentificationtype              AS "destination_reception_identification_type",
    destinationreceptionacceptationstatus               AS "destination_reception_acceptation_status",
    destinationreceptionrefusalreason                   AS "destination_reception_refusal_reason",
    destinationoperationdate                            AS "destination_operation_date",
    destinationoperationsignaturedate                   AS "destination_operation_signature_date",
    destinationoperationsignatureauthor                 AS "destination_operation_signature_author",
    destinationtype                                     AS "destination_type",
    destinationoperationnextdestinationcompanysiret     AS "destination_operation_next_destination_company_siret",
    destinationoperationnextdestinationcompanyname      AS "destination_operation_next_destination_company_name",
    destinationoperationnextdestinationcompanyaddress   AS "destination_operation_next_destination_company_address",
    destinationoperationnextdestinationcompanycontact   AS "destination_operation_next_destination_company_contact",
    destinationoperationnextdestinationcompanymail      AS "destination_operation_next_destination_company_mail",
    destinationoperationnextdestinationcompanyphone     AS "destination_operation_next_destination_company_phone",
    destinationoperationnextdestinationcompanyvatnumber AS "destination_operation_next_destination_company_vat_number",
    identificationnumbers                               AS "identification_numbers",
    identificationtype                                  AS "identification_type",
    replace(
        destinationplannedoperationcode, ' ', ''
    )                                                   AS "destination_planned_operation_code",
    replace(
        destinationoperationcode, ' ', ''
    )                                                   AS "destination_operation_code",
    weightvalue / 1000                                  AS "weight_value",
    destinationreceptionweight
    / 1000                                              AS "destination_reception_weight"
FROM
    {{ source("raw_zone_trackdechets", "bsvhu_raw") }}
