select
    "SIREN" as siren,
    "Région siège" as region_siege,
    "Département siège" as departement_siege,
    "Arrondissement siège" as arrondissement_siege,
    "Commune siège" as commune_siege,
    "Nom du groupement" as nom_du_groupement,
    "Nature juridique" as nature_juridique,
    "Syndicat à la carte"::boolean as syndicat_a_la_carte,
    "Groupement interdépartemental"::boolean as groupement_interdépartemental,
    "Date de création"::date as date_creation,
    "Date d'effet"::date as date_effet,
    "Mode de répartition des sièges" as mode_repartition_siege,
    "Autre mode de répartition des sièges" as autre_mode_repartition_siege,
    "Nombre de membres" as nombre_membres,
    population,
    "Nombre de compétences exercées" as nombre_competences_exercees,
    "Mode de financement" as mode_financement,
    "DGF Bonifiée"::boolean as dgf_bonifiee,
    dsc::boolean,
    reom::boolean,
    "Autre redevance" as autre_redevance,
    teom::boolean,
    "Autre taxe" as autre_taxe,
    "Civilité Président" as civilite_president,
    "Prénom Président" as prenom_president,
    "Nom Président" as nom_president,
    "Adresse du siège_1" as adresse_siege_1,
    "Adresse du siège_2" as adresse_siege_2,
    "Adresse du siège_3" as adresse_siege_3,
    "Code postal du siège - Ville du siège" as code_postal_ville_siege,
    "Téléphone du siège" as telephone_siege,
    "Fax du siège" as fax_siege,
    "Courriel du siège" as courriel_siege,
    "Site internet" as site_internet,
    "Adresse annexe_1" as adresse_annexe_1,
    "Adresse annexe_2" as adresse_annexe_2,
    "Adresse annexe_3" as adresse_annexe_3,
    "Code postal annexe - Ville annexe" as code_postal_ville_annexe,
    "Téléphone annexe" as telephone_annexe,
    "Fax annexe" as faxe_annexe
from
    {{ source('raw_zone_gsheet', 'collectivites') }}