select
    "codeS3ic" as code_s3ic,
    "s3icNumeroSiret" as siret,
    x::int,
    y::int,
    region::int,
    "nomEts" as nom_etablissement,
    "codeCommuneEtablissement" as code_commune_etablissement,
    "codePostal" as code_postal,
    "etatActivite"::int as etat_activite,
    "codeApe" as code_ape,
    "nomCommune" as nom_commune,
    seveso as seveso,
    regime as regime,
    "prioriteNationale"::bool as priorite_nationale,
    ippc::bool,
    "declarationAnnuelle"::bool as declaration_annuelle,
    "familleIc" as familleic,
    "baseIdService"::int as base_id_service,
    "natureIdService"::int as nature_id_service,
    adresse1 as adresse_1,
    adresse2 as adresse_2,
    "dateInspection"::date as date_inspection,
    "indicationSsp"::bool as indication_ssp,
    rayon::int,
    "precisionPositionnement"::int as precision_positionnement,
    inserted_at
from
    {{ source('raw_zone_icpe', 'etablissements') }}
