name: trackdechets_data_platform
version: "1.0"
profile: meltano
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]
model-paths:
  - models
analysis-paths:
  - analysis
test-paths:
  - tests
seed-paths:
  - data
macro-paths:
  - macros
snapshot-paths:
  - snapshots
target-path: ../output/dbt
log-path: logs
packages-install-path: dbt_packages
clean-targets:
  - ../.meltano/transformers/dbt/target
  - dbt_packages
  - logs
tests:
  +store_failures: true
flags:
  require_explicit_package_overrides_for_builtin_materializations: false
  source_freshness_run_project_hooks: True
  send_anonymous_usage_stats: False
  use_colors: True
vars:
  dbt-osmosis:
    raw_zone: "sources/raw_zone.yml"
    raw_zone_trackdechets: "sources/raw_zone_trackdechets.yml"
    raw_zone_gsheet: "sources/raw_zone_gsheet.yml"
    raw_zone_insee: "sources/raw_zone_insee.yml"
    raw_zone_icpe: "sources/raw_zone_icpe.yml"
    raw_zone_zammad: "sources/raw_zone_zammad.yml"
    raw_zone_gistrid: "sources/raw_zone_gistrid.yml"

models:
  trackdechets_data_platform:
    +dbt-osmosis: "_{model}.yml"
    refined_zone:
      analytics:
        +materialized: view
        +schema: refined_zone_analytics
        etablissements_inscrits_par_departements:
          +materialized: table
        etablissements_par_departements:
          +materialized: table

      icpe:
        +schema: refined_zone_icpe
        gerep:
          +materialized: ephemeral
        icpe_siretise:
          +materialized: table
        icpe_stats_rubriques_alinea:
          +materialized: table
        reconciliation_exutoires_georisques_td:
          +materialized: table

      enriched:
        +schema: refined_zone_enriched

      stats_publiques:
        +schema: refined_zone_stats_publiques

      gistrid:
        +schema: refined_zone_gistrid

    trusted_zone:
      +schema: trusted_zone
      gsheet:
        +schema: trusted_zone_gsheet
      insee:
        +schema: trusted_zone_insee
      trackdechets:
        +schema: trusted_zone_trackdechets
      icpe:
        +schema: trusted_zone_icpe
      zammad:
        +schema: trusted_zone_zammad
      gerep:
        +schema: trusted_zone_gerep
      gistrid:
        +schema: trusted_zone_gistrid
      rndts:
        +schema: trusted_zone_rndts
      gerico:
        +schema: trusted_zone_gerico

  elementary:
    +schema: "elementary"
